
-- ==========================  TABLES  =====================--

CREATE TABLE USER (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(64) UNIQUE,
  EMAIL VARCHAR(1024) UNIQUE
);

CREATE TABLE TAG (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE USER_AGENT (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(1024) UNIQUE NOT NULL
);

CREATE TABLE IP (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE CREDENTIAL (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  USER_AGENT_ID BIGINT(16),
  IP_ID BIGINT(16),
  SECRET VARCHAR(128),
  ACTIVATION_SECRET VARCHAR(128),
  UNIQUE KEY CREDENTIAL_UK_SECRET (USER_ID, USER_AGENT_ID, IP_ID),
  CONSTRAINT FK_SECRET_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_SECRET_IP FOREIGN KEY (IP_ID) REFERENCES IP(ID),
  CONSTRAINT FK_SECRET_USER_AGENT FOREIGN KEY (USER_AGENT_ID) REFERENCES USER_AGENT(ID)
);

CREATE TABLE PENDING_USER_UPDATE (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  UPDATE_SECRET VARCHAR(128),
  USERNAME VARCHAR(64),
  EMAIL VARCHAR(1024),
  CONSTRAINT FK_PENDING_USER_UP_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);


CREATE TABLE GROUPING (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(64),
  ADMIN_LEVEL INT(1) DEFAULT 3,
  EMAIL_NOTIFY INT(1),
  IN_APP_NOTIFY INT(1),
  IMAGE BLOB,
  CREATOR_ID BIGINT(16),
  DESCRIPTION TEXT,
  CONSTRAINT FK_GROUP_USER FOREIGN KEY (CREATOR_ID) REFERENCES USER(ID)
);

CREATE TABLE WORDS (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE EXPLANATION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  WORDS_ID BIGINT(16),
  SEARCH_WORDS_ID BIGINT(16),
  SITE_ID BIGINT(16) NOT NULL,
  CONTENT TEXT,
  GROUP_AUTHOR_ID BIGINT(16),
  AUTHOR_ID BIGINT(16),
  LAST_UPDATE DATETIME,
  CONSTRAINT FK_EXPLANATION_WORD FOREIGN KEY (WORDS_ID) REFERENCES WORDS(ID),
  CONSTRAINT FK_EXPLANATION_SEARCH_WORDS FOREIGN KEY (SEARCH_WORDS_ID) REFERENCES WORDS(ID),
  CONSTRAINT FK_EXPLANATION_GROUP FOREIGN KEY (GROUP_AUTHOR_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_EXPLANATION_USER FOREIGN KEY (AUTHOR_ID) REFERENCES USER(ID)
);

CREATE TABLE SITE_PARTS (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE TEXT NOT NULL
);

CREATE TABLE SITE (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  ONE_ID BIGINT(16),
  TWO_ID BIGINT(16),
  THREE_ID BIGINT(16),
  FOUR_ID BIGINT(16),
  CONSTRAINT FK_SITE_PARTS_1 FOREIGN KEY (ONE_ID) REFERENCES SITE_PARTS(ID),
  CONSTRAINT FK_SITE_PARTS_2 FOREIGN KEY (TWO_ID) REFERENCES SITE_PARTS(ID),
  CONSTRAINT FK_SITE_PARTS_3 FOREIGN KEY (THREE_ID) REFERENCES SITE_PARTS(ID),
  CONSTRAINT FK_SITE_PARTS_4 FOREIGN KEY (FOUR_ID) REFERENCES SITE_PARTS(ID)
);

CREATE TABLE QUESTION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  WORDS_ID BIGINT(16),
  SITE_ID BIGINT(16),
  ELABORATION VARCHAR(250),
  GROUP_ASKER_ID BIGINT(16),
  ASKER_ID BIGINT(16),
  UNCLEAR_VOTES BIGINT(16),
  ANSWERED_VOTES BIGINT(16),
  LAST_UPDATE DATETIME,
  CONSTRAINT FK_QUESTION_SITE FOREIGN KEY (SITE_ID) REFERENCES SITE(ID),
  CONSTRAINT FK_QUESTION_USER FOREIGN KEY (ASKER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_QUESTION_GROUP FOREIGN KEY (GROUP_ASKER_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_QUESTION_WORDS FOREIGN KEY (WORDS_ID) REFERENCES WORDS(ID)
);

CREATE TABLE COMMENT_TAG_FOLLOWER (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  TAG_ID BIGINT(16),
  USER_ID BIGINT(16),
  UNIQUE KEY COMMENT_TAG_FOLLOWER_UNQ_ID (USER_ID, TAG_ID),
  CONSTRAINT FK_COMMENT_TAG_FOLLOWER_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG(ID),
  CONSTRAINT FK_COMMENT_TAG_FOLLOWER_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE QUESTION_TAG_FOLLOWER (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  TAG_ID BIGINT(16),
  USER_ID BIGINT(16),
  UNIQUE KEY QUESTION_TAG_FOLLOWER_UNQ_ID (USER_ID, TAG_ID),
  CONSTRAINT FK_QUESTION_TAG_FOLLOWER_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG(ID),
  CONSTRAINT FK_QUESTION_TAG_FOLLOWER_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE EXPLANATION_TAG_FOLLOWER (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  TAG_ID BIGINT(16),
  USER_ID BIGINT(16),
  UNIQUE KEY EXPLANATION_TAG_FOLLOWER_UNQ_ID (USER_ID, TAG_ID),
  CONSTRAINT FK_EXPLANATION_TAG_FOLLOWER_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG(ID),
  CONSTRAINT FK_EXPLANATION_TAG_FOLLOWER_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE GROUP_FOLLOWER (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  GROUP_ID BIGINT(16),
  USER_ID BIGINT(16),
  UNIQUE KEY GROUP_FOLLOWER_UNQ_ID (USER_ID, GROUP_ID),
  CONSTRAINT FK_GROUP_FOLLOWER_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_GROUP_FOLLOWER_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE FOLLOWER (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  TARGET_ID BIGINT(16),
  USER_ID BIGINT(16),
  UNIQUE KEY GROUP_FOLLOWER_UNQ_ID (USER_ID, TARGET_ID),
  CONSTRAINT FK_FOLLOWER_TARGET FOREIGN KEY (TARGET_ID) REFERENCES USER(ID),
  CONSTRAINT FK_FOLLOWER_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);


CREATE TABLE EXPLANATION_COMMENT (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  EXPLANATION_ID BIGINT(16),
  COMMENT_ID BIGINT(16),
  SITE_ID BIGINT(16),
  AUTHOR_ID BIGINT(16),
  VALUE TEXT,
  LAST_UPDATE DATETIME,
  GROUP_AUTHOR_ID BIGINT(16),
  CONSTRAINT FK_COMMENT_GROUP FOREIGN KEY (GROUP_AUTHOR_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_COMMENT_COMMENT FOREIGN KEY (COMMENT_ID) REFERENCES EXPLANATION_COMMENT(ID),
  CONSTRAINT FK_COMMENT_SITE FOREIGN KEY (SITE_ID) REFERENCES SITE(ID),
  CONSTRAINT FK_COMMENT_USER FOREIGN KEY (AUTHOR_ID) REFERENCES USER(ID),
  CONSTRAINT FK_COMMENT_EXPLANATION FOREIGN KEY (EXPLANATION_ID) REFERENCES EXPLANATION(ID)
);

CREATE TABLE QUESTION_COMMENT (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  QUESTION_ID BIGINT(16),
  COMMENT_ID BIGINT(16),
  AUTHOR_ID BIGINT(16),
  GROUP_AUTHOR_ID BIGINT(16),
  VALUE TEXT,
  LAST_UPDATE DATETIME,
  CONSTRAINT FK_QCOMMENT_QCOMMENT FOREIGN KEY (COMMENT_ID) REFERENCES QUESTION_COMMENT(ID),
  CONSTRAINT FK_QCOMMENT_USER FOREIGN KEY (AUTHOR_ID) REFERENCES USER(ID),
  CONSTRAINT FK_QCOMMENT_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID)
);

CREATE TABLE OPINION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  EXPLANATION_ID BIGINT(16),
  SITE_ID BIGINT(16),
  FAVORABLE INT(1),
  UNIQUE KEY OPINION_UNQ_USER_SITE_EXPL (USER_ID, SITE_ID, EXPLANATION_ID),
  CONSTRAINT FK_OPINION_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_OPINION_EXPL FOREIGN KEY (EXPLANATION_ID) REFERENCES EXPLANATION(ID),
  CONSTRAINT FK_OPINION_SITE FOREIGN KEY (SITE_ID) REFERENCES SITE(ID)
);

CREATE TABLE SITE_EXPLANATION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  SITE_ID BIGINT(16),
  EXPLANATION_ID BIGINT(16),
  UNIQUE KEY SITE_EXPLANATION_UNQ_SITE_EXPLANATION (SITE_ID, EXPLANATION_ID),
  CONSTRAINT FK_SITE_ITEM_SITE FOREIGN KEY (SITE_ID) REFERENCES SITE(ID),
  CONSTRAINT FK_SITE_ITEM_EXPL FOREIGN KEY (EXPLANATION_ID) REFERENCES EXPLANATION(ID)
);

CREATE TABLE EXPLANATION_COMMENT_TAG (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  REFERENCE_ID BIGINT(16),
  TAG_ID BIGINT(16),
  CONSTRAINT FK_COMMENT_TAG_REF_ID FOREIGN KEY (REFERENCE_ID) REFERENCES EXPLANATION_COMMENT(ID),
  CONSTRAINT FK_COMMENT_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

CREATE TABLE QUESTION_TAG (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  REFERENCE_ID BIGINT(16),
  TAG_ID BIGINT(16),
  CONSTRAINT FK_QUESTION_TAG_REF_ID FOREIGN KEY (REFERENCE_ID) REFERENCES QUESTION(ID),
  CONSTRAINT FK_QUESTION_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

CREATE TABLE QUESTION_COMMENT_TAG (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  REFERENCE_ID BIGINT(16),
  TAG_ID BIGINT(16),
  CONSTRAINT FK_QUESTION_COMMENT_TAG_REF_ID FOREIGN KEY (REFERENCE_ID) REFERENCES QUESTION(ID),
  CONSTRAINT FK_QUESTION_COMMENT_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

CREATE TABLE GROUP_TAG (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  REFERENCE_ID BIGINT(16),
  TAG_ID BIGINT(16),
  CONSTRAINT FK_GROUP_TAG_REF_ID FOREIGN KEY (REFERENCE_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_GROUP_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

CREATE TABLE EXPLANATION_TAG (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  REFERENCE_ID BIGINT(16),
  TAG_ID BIGINT(16),
  CONSTRAINT FK_EXPLANATION_TAG_REF_ID FOREIGN KEY (REFERENCE_ID) REFERENCES EXPLANATION(ID),
  CONSTRAINT FK_EXPLANATION_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

CREATE TABLE GROUP_CONTRIBUTOR (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  LEVEL INT(1),
  EMAIL_NOTIFY INT(1),
  IN_APP_NOTIFY INT(1),
  GROUP_ID BIGINT(16),
  USER_ID BIGINT(16),
  UNIQUE KEY GROUP_CONTRIBUTOR_UNQ_KEY (GROUP_ID, USER_ID),
  CONSTRAINT FK_GROUP_CONTRIBUTOR_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_GROUP_CONTRIBUTOR_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE GROUPED_EXPLANATION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  GROUP_ID BIGINT(16),
  EXPLANATION_ID BIGINT(16),
  UNIQUE KEY GROUP_EXPLANATION_UNQ_GROUP_EXPLANATION (GROUP_ID, EXPLANATION_ID),
  CONSTRAINT FK_GROUPED_EXPLANATION_ITEM_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_GROUPED_EXPLANATION_ITEM_EXPL FOREIGN KEY (EXPLANATION_ID) REFERENCES EXPLANATION(ID)
);

CREATE TABLE GROUPED_OPINION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  GROUP_ID BIGINT(16),
  EXPLANATION_ID BIGINT(16),
  LYKE INT(1),
  DISLIKE INT(1),
  UNIQUE KEY GROUPED_OPINION_UNQ_USER_SITE_EXPL (USER_ID, GROUP_ID, EXPLANATION_ID),
  CONSTRAINT FK_GROUPED_OPINION_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_GROUPED_OPINION_EXPL FOREIGN KEY (EXPLANATION_ID) REFERENCES EXPLANATION(ID),
  CONSTRAINT FK_GROUPED_OPINION_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPING(ID)
);

CREATE TABLE OPEN_SITE (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  URL TEXT NOT NULL,
  CONSTRAINT FK_OPEN_SITES_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE QUESTION_OPINION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  QUESTION_ID BIGINT(16),
  UNCLEAR INT(1),
  ANSWERED INT(1),
  UNIQUE KEY QOPINION_UNQ_USER_QUESTION (USER_ID, QUESTION_ID),
  CONSTRAINT FK_QOPINION_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_QOPINION_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID)
);

CREATE TABLE NOTIFICATION_TYPE (
  ID INT(1) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(32)
);

CREATE TABLE NOTIFICATION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  TYPE_ID INT(1) NOT NULL,
  USER_ID BIGINT(16),
  SEEN INT(1) DEFAULT 0,
  POPPEDUP INT(1) DEFAULT 0,
  AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  SITE_ID BIGINT(16),
  QUESTION_ID BIGINT(16),
  EXPLANATION_COMMENT_ID BIGINT(16),
  QUESTION_COMMENT_ID BIGINT(16),
  EXPLANATION_ID BIGINT(16),
  CONSTRAINT FK_NOTIFICATION_TYPE FOREIGN KEY (TYPE_ID) REFERENCES NOTIFICATION_TYPE(ID),
  CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_NOTIFICATION_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID),
  CONSTRAINT FK_NOTIFICATION_EXPL_COMMENT FOREIGN KEY (EXPLANATION_COMMENT_ID) REFERENCES EXPLANATION_COMMENT(ID),
  CONSTRAINT FK_NOTIFICATION_Q_COMMENT FOREIGN KEY (QUESTION_COMMENT_ID) REFERENCES QUESTION_COMMENT(ID),
  CONSTRAINT FK_NOTIFICATION_EXPL FOREIGN KEY (EXPLANATION_ID) REFERENCES EXPLANATION(ID)
);
