
-- ==========================  Views  =====================--

CREATE OR REPLACE VIEW USER_DETAIL
AS
  SELECT
    USER.*,
    IFNULL(LIKES.LIKES, 0) AS LIKES,
    IFNULL(DISLIKES.DISLIKES, 0) AS DISLIKES
    FROM USER
  LEFT JOIN
    (select USER_ID, COUNT(*) AS LIKES from OPINION
      WHERE FAVORABLE = 1 GROUP BY USER_ID, FAVORABLE) AS LIKES
  ON LIKES.USER_ID = ID
  LEFT JOIN
    (select USER_ID, COUNT(*) AS DISLIKES from OPINION
      WHERE FAVORABLE = 0 GROUP BY USER_ID, FAVORABLE) AS DISLIKES
  ON DISLIKES.USER_ID = LIKES.USER_ID;


CREATE OR REPLACE VIEW EXPLANATION_DETAIL
AS
  SELECT
  EXPLANATION.*,
  IFNULL(LIKES.LIKES, 0) AS LIKES,
  IFNULL(DISLIKES.DISLIKES, 0) AS DISLIKES
  FROM EXPLANATION
  LEFT JOIN
    (select EXPLANATION_ID, COUNT(*) AS LIKES from OPINION
      WHERE FAVORABLE = 1 GROUP BY EXPLANATION_ID, FAVORABLE) AS LIKES
  ON LIKES.EXPLANATION_ID = ID
  LEFT JOIN
    (select EXPLANATION_ID, COUNT(*) AS DISLIKES from OPINION
      WHERE FAVORABLE = 0 GROUP BY EXPLANATION_ID, FAVORABLE) AS DISLIKES
  ON DISLIKES.EXPLANATION_ID = ID;


CREATE OR REPLACE VIEW SITE_EXPLANATION_DETAIL
AS
    SELECT
        SITE_EXPLANATION.*,
        SITE.URL,
    		IFNULL(LIKES.LIKES, 0) AS LIKES,
    		IFNULL(DISLIKES.DISLIKES, 0) AS DISLIKES
    FROM SITE_EXPLANATION LEFT JOIN
    	(SELECT EXPLANATION_ID, COUNT(*) AS LIKES, SITE_ID FROM OPINION
    		WHERE FAVORABLE=1
    		GROUP BY EXPLANATION_ID, FAVORABLE, SITE_ID) AS LIKES
    	ON LIKES.EXPLANATION_ID=SITE_EXPLANATION.EXPLANATION_ID AND
			SITE_EXPLANATION.SITE_ID=LIKES.SITE_ID
    	LEFT JOIN (SELECT EXPLANATION_ID, COUNT(*) AS DISLIKES, SITE_ID FROM OPINION
    		WHERE FAVORABLE=0
    		GROUP BY EXPLANATION_ID, FAVORABLE, SITE_ID) AS DISLIKES
    	ON DISLIKES.EXPLANATION_ID=SITE_EXPLANATION.EXPLANATION_ID AND
			DISLIKES.SITE_ID = SITE_EXPLANATION.SITE_ID
        LEFT JOIN SITE ON SITE.ID = SITE_EXPLANATION.SITE_ID;


CREATE OR REPLACE VIEW EXPLANATION_UPDATE
AS
	SELECT ID, AUTHOR_ID AS COMMENT_AUTHOR_ID, ASKER_ID, EXPLANATION_ID, EXPL_AUTHOR_ID FROM
	(SELECT * FROM COMMENT AS COM
		JOIN (SELECT ID AS EXPL_ID, WORDS_ID, AUTHOR_ID AS EXPL_AUTHOR_ID FROM EXPLANATION) AS EXPL
			ON COM.EXPLANATION_ID = EXPL.EXPL_ID
		LEFT JOIN (SELECT ASKER_ID, SITE_ID AS Q_SITE_ID, WORDS_ID AS Q_WORDS_ID FROM QUESTION) AS QS
			ON QS.Q_SITE_ID = COM.SITE_ID AND EXPL.WORDS_ID = QS.Q_WORDS_ID) AS FINAL
