
-- ==========================  VALUES  =====================--

INSERT INTO NOTIFICATION_TYPE (ID, VALUE) VALUES (1, 'Explanation');
INSERT INTO NOTIFICATION_TYPE (ID, VALUE) VALUES (2, 'ExplanationComment');
INSERT INTO NOTIFICATION_TYPE (ID, VALUE) VALUES (3, 'Question');
INSERT INTO NOTIFICATION_TYPE (ID, VALUE) VALUES (4, 'QuestionComment');

INSERT INTO SITE_PARTS (ID, VALUE) VALUES (1, 'http://');
INSERT INTO SITE_PARTS (ID, VALUE) VALUES (2, 'https://');
