


-- ==========================  USERS  =====================--

DROP DATABASE IF EXISTS CE;
DROP USER IF EXISTS 'CE'@'localhost';

CREATE USER 'CE'@'localhost' IDENTIFIED BY 'ITSJUSTATESTDB';

CREATE DATABASE CE;

GRANT ALL PRIVILEGES ON CE.* TO 'CE'@'localhost';

USE CE;

-- ==========================  SEQUENCES  =====================--

-- CREATE SEQUENCE USER_ID_SEQ START WITH 1050;
-- CREATE SEQUENCE COMPANY_ID_SEQ START WITH 1250;
-- CREATE SEQUENCE FACILITY_ID_SEQ START WITH 10050;
-- CREATE SEQUENCE TASK_ID_SEQ START WITH 1250;
-- CREATE SEQUENCE USER_TASK_ID_SEQ START WITH 71250;
-- CREATE SEQUENCE TIME_SUBMISSION_ID_SEQ START WITH 10050;

-- ==========================  TABLES  =====================--

CREATE TABLE USER (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(64) UNIQUE,
  EMAIL VARCHAR(1024) UNIQUE
);

CREATE TABLE TAG (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE USER_AGENT (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(1024) UNIQUE NOT NULL
);

CREATE TABLE IP (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE CREDENTIAL (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  USER_AGENT_ID BIGINT(16),
  IP_ID BIGINT(16),
  SECRET VARCHAR(128),
  ACTIVATION_SECRET VARCHAR(128),
  UNIQUE KEY CREDENTIAL_UK_SECRET (USER_ID, USER_AGENT_ID, IP_ID),
  CONSTRAINT FK_SECRET_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_SECRET_IP FOREIGN KEY (IP_ID) REFERENCES IP(ID),
  CONSTRAINT FK_SECRET_USER_AGENT FOREIGN KEY (USER_AGENT_ID) REFERENCES USER_AGENT(ID)
);

CREATE TABLE PENDING_USER_UPDATE (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  UPDATE_SECRET VARCHAR(128),
  USERNAME VARCHAR(64),
  EMAIL VARCHAR(1024),
  CONSTRAINT FK_PENDING_USER_UP_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);


CREATE TABLE GROUPING (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(64),
  ADMIN_LEVEL INT(1) DEFAULT 3,
  EMAIL_NOTIFY INT(1),
  IN_APP_NOTIFY INT(1),
  IMAGE BLOB,
  CREATOR_ID BIGINT(16),
  DESCRIPTION TEXT,
  CONSTRAINT FK_GROUP_USER FOREIGN KEY (CREATOR_ID) REFERENCES USER(ID)
);

CREATE TABLE WORDS (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE EXPLANATION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  WORDS_ID BIGINT(16),
  SEARCH_WORDS_ID BIGINT(16),
  SITE_ID BIGINT(16) NOT NULL,
  CONTENT TEXT,
  GROUP_AUTHOR_ID BIGINT(16),
  AUTHOR_ID BIGINT(16),
  LAST_UPDATE DATETIME,
  CONSTRAINT FK_EXPLANATION_WORD FOREIGN KEY (WORDS_ID) REFERENCES WORDS(ID),
  CONSTRAINT FK_EXPLANATION_SEARCH_WORDS FOREIGN KEY (SEARCH_WORDS_ID) REFERENCES WORDS(ID),
  CONSTRAINT FK_EXPLANATION_GROUP FOREIGN KEY (GROUP_AUTHOR_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_EXPLANATION_USER FOREIGN KEY (AUTHOR_ID) REFERENCES USER(ID)
);

CREATE TABLE SITE_PARTS (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  VALUE TEXT NOT NULL
);

CREATE TABLE SITE (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  ONE_ID BIGINT(16),
  TWO_ID BIGINT(16),
  THREE_ID BIGINT(16),
  FOUR_ID BIGINT(16),
  CONSTRAINT FK_SITE_PARTS_1 FOREIGN KEY (ONE_ID) REFERENCES SITE_PARTS(ID),
  CONSTRAINT FK_SITE_PARTS_2 FOREIGN KEY (TWO_ID) REFERENCES SITE_PARTS(ID),
  CONSTRAINT FK_SITE_PARTS_3 FOREIGN KEY (THREE_ID) REFERENCES SITE_PARTS(ID),
  CONSTRAINT FK_SITE_PARTS_4 FOREIGN KEY (FOUR_ID) REFERENCES SITE_PARTS(ID)
);

CREATE TABLE QUESTION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  WORDS_ID BIGINT(16),
  SITE_ID BIGINT(16),
  ELABORATION VARCHAR(250),
  GROUP_ASKER_ID BIGINT(16),
  ASKER_ID BIGINT(16),
  UNCLEAR_VOTES BIGINT(16),
  ANSWERED_VOTES BIGINT(16),
  LAST_UPDATE DATETIME,
  CONSTRAINT FK_QUESTION_SITE FOREIGN KEY (SITE_ID) REFERENCES SITE(ID),
  CONSTRAINT FK_QUESTION_USER FOREIGN KEY (ASKER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_QUESTION_GROUP FOREIGN KEY (GROUP_ASKER_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_QUESTION_WORDS FOREIGN KEY (WORDS_ID) REFERENCES WORDS(ID)
);

CREATE TABLE COMMENT_TAG_FOLLOWER (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  TAG_ID BIGINT(16),
  USER_ID BIGINT(16),
  UNIQUE KEY COMMENT_TAG_FOLLOWER_UNQ_ID (USER_ID, TAG_ID),
  CONSTRAINT FK_COMMENT_TAG_FOLLOWER_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG(ID),
  CONSTRAINT FK_COMMENT_TAG_FOLLOWER_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE QUESTION_TAG_FOLLOWER (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  TAG_ID BIGINT(16),
  USER_ID BIGINT(16),
  UNIQUE KEY QUESTION_TAG_FOLLOWER_UNQ_ID (USER_ID, TAG_ID),
  CONSTRAINT FK_QUESTION_TAG_FOLLOWER_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG(ID),
  CONSTRAINT FK_QUESTION_TAG_FOLLOWER_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE EXPLANATION_TAG_FOLLOWER (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  TAG_ID BIGINT(16),
  USER_ID BIGINT(16),
  UNIQUE KEY EXPLANATION_TAG_FOLLOWER_UNQ_ID (USER_ID, TAG_ID),
  CONSTRAINT FK_EXPLANATION_TAG_FOLLOWER_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG(ID),
  CONSTRAINT FK_EXPLANATION_TAG_FOLLOWER_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE GROUP_FOLLOWER (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  GROUP_ID BIGINT(16),
  USER_ID BIGINT(16),
  UNIQUE KEY GROUP_FOLLOWER_UNQ_ID (USER_ID, GROUP_ID),
  CONSTRAINT FK_GROUP_FOLLOWER_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_GROUP_FOLLOWER_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE FOLLOWER (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  TARGET_ID BIGINT(16),
  USER_ID BIGINT(16),
  UNIQUE KEY GROUP_FOLLOWER_UNQ_ID (USER_ID, TARGET_ID),
  CONSTRAINT FK_FOLLOWER_TARGET FOREIGN KEY (TARGET_ID) REFERENCES USER(ID),
  CONSTRAINT FK_FOLLOWER_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);


CREATE TABLE EXPLANATION_COMMENT (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  EXPLANATION_ID BIGINT(16),
  COMMENT_ID BIGINT(16),
  SITE_ID BIGINT(16),
  AUTHOR_ID BIGINT(16),
  VALUE TEXT,
  LAST_UPDATE DATETIME,
  GROUP_AUTHOR_ID BIGINT(16),
  CONSTRAINT FK_COMMENT_GROUP FOREIGN KEY (GROUP_AUTHOR_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_COMMENT_COMMENT FOREIGN KEY (COMMENT_ID) REFERENCES EXPLANATION_COMMENT(ID),
  CONSTRAINT FK_COMMENT_SITE FOREIGN KEY (SITE_ID) REFERENCES SITE(ID),
  CONSTRAINT FK_COMMENT_USER FOREIGN KEY (AUTHOR_ID) REFERENCES USER(ID),
  CONSTRAINT FK_COMMENT_EXPLANATION FOREIGN KEY (EXPLANATION_ID) REFERENCES EXPLANATION(ID)
);

CREATE TABLE QUESTION_COMMENT (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  QUESTION_ID BIGINT(16),
  COMMENT_ID BIGINT(16),
  AUTHOR_ID BIGINT(16),
  GROUP_AUTHOR_ID BIGINT(16),
  VALUE TEXT,
  LAST_UPDATE DATETIME,
  CONSTRAINT FK_QCOMMENT_QCOMMENT FOREIGN KEY (COMMENT_ID) REFERENCES QUESTION_COMMENT(ID),
  CONSTRAINT FK_QCOMMENT_USER FOREIGN KEY (AUTHOR_ID) REFERENCES USER(ID),
  CONSTRAINT FK_QCOMMENT_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID)
);

CREATE TABLE OPINION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  EXPLANATION_ID BIGINT(16),
  SITE_ID BIGINT(16),
  FAVORABLE INT(1),
  UNIQUE KEY OPINION_UNQ_USER_SITE_EXPL (USER_ID, SITE_ID, EXPLANATION_ID),
  CONSTRAINT FK_OPINION_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_OPINION_EXPL FOREIGN KEY (EXPLANATION_ID) REFERENCES EXPLANATION(ID),
  CONSTRAINT FK_OPINION_SITE FOREIGN KEY (SITE_ID) REFERENCES SITE(ID)
);

CREATE TABLE SITE_EXPLANATION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  SITE_ID BIGINT(16),
  EXPLANATION_ID BIGINT(16),
  UNIQUE KEY SITE_EXPLANATION_UNQ_SITE_EXPLANATION (SITE_ID, EXPLANATION_ID),
  CONSTRAINT FK_SITE_ITEM_SITE FOREIGN KEY (SITE_ID) REFERENCES SITE(ID),
  CONSTRAINT FK_SITE_ITEM_EXPL FOREIGN KEY (EXPLANATION_ID) REFERENCES EXPLANATION(ID)
);

CREATE TABLE EXPLANATION_COMMENT_TAG (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  REFERENCE_ID BIGINT(16),
  TAG_ID BIGINT(16),
  CONSTRAINT FK_COMMENT_TAG_REF_ID FOREIGN KEY (REFERENCE_ID) REFERENCES EXPLANATION_COMMENT(ID),
  CONSTRAINT FK_COMMENT_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

CREATE TABLE QUESTION_TAG (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  REFERENCE_ID BIGINT(16),
  TAG_ID BIGINT(16),
  CONSTRAINT FK_QUESTION_TAG_REF_ID FOREIGN KEY (REFERENCE_ID) REFERENCES QUESTION(ID),
  CONSTRAINT FK_QUESTION_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

CREATE TABLE QUESTION_COMMENT_TAG (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  REFERENCE_ID BIGINT(16),
  TAG_ID BIGINT(16),
  CONSTRAINT FK_QUESTION_COMMENT_TAG_REF_ID FOREIGN KEY (REFERENCE_ID) REFERENCES QUESTION(ID),
  CONSTRAINT FK_QUESTION_COMMENT_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

CREATE TABLE GROUP_TAG (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  REFERENCE_ID BIGINT(16),
  TAG_ID BIGINT(16),
  CONSTRAINT FK_GROUP_TAG_REF_ID FOREIGN KEY (REFERENCE_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_GROUP_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

CREATE TABLE EXPLANATION_TAG (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  REFERENCE_ID BIGINT(16),
  TAG_ID BIGINT(16),
  CONSTRAINT FK_EXPLANATION_TAG_REF_ID FOREIGN KEY (REFERENCE_ID) REFERENCES EXPLANATION(ID),
  CONSTRAINT FK_EXPLANATION_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

CREATE TABLE GROUP_CONTRIBUTOR (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  LEVEL INT(1),
  EMAIL_NOTIFY INT(1),
  IN_APP_NOTIFY INT(1),
  GROUP_ID BIGINT(16),
  USER_ID BIGINT(16),
  UNIQUE KEY GROUP_CONTRIBUTOR_UNQ_KEY (GROUP_ID, USER_ID),
  CONSTRAINT FK_GROUP_CONTRIBUTOR_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_GROUP_CONTRIBUTOR_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE GROUPED_EXPLANATION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  GROUP_ID BIGINT(16),
  EXPLANATION_ID BIGINT(16),
  UNIQUE KEY GROUP_EXPLANATION_UNQ_GROUP_EXPLANATION (GROUP_ID, EXPLANATION_ID),
  CONSTRAINT FK_GROUPED_EXPLANATION_ITEM_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPING(ID),
  CONSTRAINT FK_GROUPED_EXPLANATION_ITEM_EXPL FOREIGN KEY (EXPLANATION_ID) REFERENCES EXPLANATION(ID)
);

CREATE TABLE GROUPED_OPINION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  GROUP_ID BIGINT(16),
  EXPLANATION_ID BIGINT(16),
  LYKE INT(1),
  DISLIKE INT(1),
  UNIQUE KEY GROUPED_OPINION_UNQ_USER_SITE_EXPL (USER_ID, GROUP_ID, EXPLANATION_ID),
  CONSTRAINT FK_GROUPED_OPINION_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_GROUPED_OPINION_EXPL FOREIGN KEY (EXPLANATION_ID) REFERENCES EXPLANATION(ID),
  CONSTRAINT FK_GROUPED_OPINION_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPING(ID)
);

CREATE TABLE OPEN_SITE (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  URL TEXT NOT NULL,
  CONSTRAINT FK_OPEN_SITES_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE QUESTION_OPINION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT(16),
  QUESTION_ID BIGINT(16),
  UNCLEAR INT(1),
  ANSWERED INT(1),
  UNIQUE KEY QOPINION_UNQ_USER_QUESTION (USER_ID, QUESTION_ID),
  CONSTRAINT FK_QOPINION_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_QOPINION_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID)
);

CREATE TABLE NOTIFICATION_TYPE (
  ID INT(1) PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(32)
);

CREATE TABLE NOTIFICATION (
  ID BIGINT(16) PRIMARY KEY AUTO_INCREMENT,
  TYPE_ID INT(1) NOT NULL,
  USER_ID BIGINT(16),
  SEEN INT(1) DEFAULT 0,
  POPPEDUP INT(1) DEFAULT 0,
  AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  SITE_ID BIGINT(16),
  QUESTION_ID BIGINT(16),
  EXPLANATION_COMMENT_ID BIGINT(16),
  QUESTION_COMMENT_ID BIGINT(16),
  EXPLANATION_ID BIGINT(16),
  CONSTRAINT FK_NOTIFICATION_TYPE FOREIGN KEY (TYPE_ID) REFERENCES NOTIFICATION_TYPE(ID),
  CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_NOTIFICATION_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID),
  CONSTRAINT FK_NOTIFICATION_EXPL_COMMENT FOREIGN KEY (EXPLANATION_COMMENT_ID) REFERENCES EXPLANATION_COMMENT(ID),
  CONSTRAINT FK_NOTIFICATION_Q_COMMENT FOREIGN KEY (QUESTION_COMMENT_ID) REFERENCES QUESTION_COMMENT(ID),
  CONSTRAINT FK_NOTIFICATION_EXPL FOREIGN KEY (EXPLANATION_ID) REFERENCES EXPLANATION(ID)
);

-- ==========================  FUNCTIONS  =====================--

set @row_num = -1;

DELIMITER $$
CREATE FUNCTION ROW_INDEX()
RETURNS BIGINT(16)
DETERMINISTIC
BEGIN
SET @row_num = @row_num + 1;
IF @row_num > 9999999 THEN
	SET @row_num = -1;
END IF;
RETURN (@row_num);
END$$

-- ==========================  Views  =====================--

CREATE OR REPLACE VIEW SITE_DETAIL
AS
SELECT S.*,
    CONCAT(IFNULL(SP1.VALUE, ""),
        IFNULL(SP2.VALUE, ""),
        IFNULL(SP3.VALUE, ""),
        IFNULL(SP4.VALUE, "")) AS URL,
    SP2.VALUE AS HEART
  FROM SITE AS S
  LEFT JOIN SITE_PARTS AS SP1 ON SP1.ID = S.ONE_ID
  LEFT JOIN SITE_PARTS AS SP2 ON SP2.ID = S.TWO_ID
  LEFT JOIN SITE_PARTS AS SP3 ON SP3.ID = S.THREE_ID
  LEFT JOIN SITE_PARTS AS SP4 ON SP4.ID = S.FOUR_ID;

CREATE OR REPLACE VIEW USER_DETAIL
AS
  SELECT
    USER.*,
    IFNULL(LIKES.LIKES, 0) AS LIKES,
    IFNULL(DISLIKES.DISLIKES, 0) AS DISLIKES
    FROM USER
  LEFT JOIN
    (select USER_ID, COUNT(*) AS LIKES from OPINION
      WHERE FAVORABLE = 1 GROUP BY USER_ID, FAVORABLE) AS LIKES
  ON LIKES.USER_ID = ID
  LEFT JOIN
    (select USER_ID, COUNT(*) AS DISLIKES from OPINION
      WHERE FAVORABLE = 0 GROUP BY USER_ID, FAVORABLE) AS DISLIKES
  ON DISLIKES.USER_ID = LIKES.USER_ID;


CREATE OR REPLACE VIEW EXPLANATION_DETAIL
AS
  SELECT
  EXPLANATION.*,
  IFNULL(LIKES.LIKES, 0) AS LIKES,
  IFNULL(DISLIKES.DISLIKES, 0) AS DISLIKES
  FROM EXPLANATION
  LEFT JOIN
    (select EXPLANATION_ID, COUNT(*) AS LIKES from OPINION
      WHERE FAVORABLE = 1 GROUP BY EXPLANATION_ID, FAVORABLE) AS LIKES
  ON LIKES.EXPLANATION_ID = ID
  LEFT JOIN
    (select EXPLANATION_ID, COUNT(*) AS DISLIKES from OPINION
      WHERE FAVORABLE = 0 GROUP BY EXPLANATION_ID, FAVORABLE) AS DISLIKES
  ON DISLIKES.EXPLANATION_ID = ID;


CREATE OR REPLACE VIEW SITE_EXPLANATION_DETAIL
AS
  SELECT
      SITE_EXPLANATION.*,
      SITE.URL,
      IFNULL(LIKES.LIKES, 0) AS LIKES,
      IFNULL(DISLIKES.DISLIKES, 0) AS DISLIKES
  FROM SITE_EXPLANATION LEFT JOIN
    (SELECT EXPLANATION_ID, COUNT(*) AS LIKES, SITE_ID FROM OPINION
      WHERE FAVORABLE=1
      GROUP BY EXPLANATION_ID, FAVORABLE, SITE_ID) AS LIKES
    ON LIKES.EXPLANATION_ID=SITE_EXPLANATION.EXPLANATION_ID AND
    SITE_EXPLANATION.SITE_ID=LIKES.SITE_ID
    LEFT JOIN (SELECT EXPLANATION_ID, COUNT(*) AS DISLIKES, SITE_ID FROM OPINION
      WHERE FAVORABLE=0
      GROUP BY EXPLANATION_ID, FAVORABLE, SITE_ID) AS DISLIKES
    ON DISLIKES.EXPLANATION_ID=SITE_EXPLANATION.EXPLANATION_ID AND
    DISLIKES.SITE_ID = SITE_EXPLANATION.SITE_ID
      LEFT JOIN SITE_DETAIL AS SITE ON SITE.ID = SITE_EXPLANATION.SITE_ID;

CREATE OR REPLACE VIEW EXPLANATION_CONNECTIONS
AS
  SELECT EXPL.ID AS EXPLANATION_ID,
        F.USER_ID AS AUTHOR_FOLLOWER_ID,
        GF.USER_ID AS GROUP_FOLLOWER_ID,
        ETF.USER_ID AS TAG_FOLLOWER_ID,
        C.AUTHOR_ID AS COMMENT_AUTHOR_ID,
        GC.USER_ID AS GROUP_CONTRIBUTOR_ID,
        Q.ASKER_ID AS QUESTION_ASKER_ID
        FROM EXPLANATION AS EXPL
        LEFT JOIN FOLLOWER AS F ON EXPL.AUTHOR_ID = F.TARGET_ID
        LEFT JOIN GROUP_FOLLOWER AS GF ON EXPL.GROUP_AUTHOR_ID = GF.GROUP_ID
        LEFT JOIN EXPLANATION_TAG AS ET ON ET.REFERENCE_ID = EXPL.ID
      	LEFT JOIN EXPLANATION_TAG_FOLLOWER AS ETF ON ETF.TAG_ID = ET.TAG_ID
        LEFT JOIN EXPLANATION_COMMENT AS C ON EXPL.ID = C.EXPLANATION_ID
        LEFT JOIN GROUPING AS G ON G.ID = C.GROUP_AUTHOR_ID OR G.ID = C.GROUP_AUTHOR_ID
        LEFT JOIN GROUP_CONTRIBUTOR AS GC ON GC.GROUP_ID = G.ID
        LEFT JOIN QUESTION AS Q ON EXPL.WORDS_ID = Q.WORDS_ID;

CREATE OR REPLACE VIEW QUESTION_CONNECTIONS
AS
  SELECT Q.ID AS QUESTION_ID,
        F.USER_ID AS ASKER_FOLLOWER_ID,
        GF.USER_ID AS GROUP_FOLLOWER_ID,
        QTF.USER_ID AS TAG_FOLLOWER_ID,
        QC.AUTHOR_ID AS COMMENT_AUTHOR_ID,
        GC.USER_ID AS GROUP_CONTRIBUTOR_ID
        FROM QUESTION AS Q
        LEFT JOIN FOLLOWER AS F ON Q.ASKER_ID = F.TARGET_ID
        LEFT JOIN GROUP_FOLLOWER AS GF ON Q.GROUP_ASKER_ID = GF.GROUP_ID
        LEFT JOIN QUESTION_TAG AS QT ON QT.REFERENCE_ID = Q.ID
      	LEFT JOIN QUESTION_TAG_FOLLOWER AS QTF ON QTF.TAG_ID = QT.TAG_ID
        LEFT JOIN QUESTION_COMMENT AS QC ON Q.ID = QC.QUESTION_ID
        LEFT JOIN GROUPING AS G ON G.ID = QC.GROUP_AUTHOR_ID
        LEFT JOIN GROUP_CONTRIBUTOR AS GC ON GC.GROUP_ID = G.ID;

CREATE OR REPLACE VIEW EXPLANATION_COMMENT_CONNECTIONS
AS
  SELECT C.ID AS COMMENT_ID,
        EXPL.AUTHOR_ID AS EXPLANATION_AUTHOR_ID,
        CP.AUTHOR_ID AS PARENT_COMMENT_AUTHOR_ID,
				CS.AUTHOR_ID AS SIBLING_COMMENT_AUTHOR_ID,
        CC.AUTHOR_ID AS CHILD_COMMENT_AUTHOR_ID,
				GC.USER_ID AS GROUP_CONTRIBUTOR_ID,
        F.USER_ID AS AUTHOR_FOLLOWER_ID,
        GF.USER_ID AS GROUP_FOLLOWER_ID,
        CTF.USER_ID AS TAG_FOLLOWER_ID
        FROM EXPLANATION_COMMENT AS C
        LEFT JOIN EXPLANATION AS EXPL ON EXPL.ID = C.EXPLANATION_ID
        LEFT JOIN EXPLANATION_COMMENT AS CP ON CP.ID = C.COMMENT_ID
				LEFT JOIN EXPLANATION_COMMENT AS CS ON C.COMMENT_ID = CS.COMMENT_ID
        LEFT JOIN EXPLANATION_COMMENT AS CC ON C.ID = CC.COMMENT_ID
				LEFT JOIN GROUPING AS G ON G.ID = EXPL.GROUP_AUTHOR_ID OR G.ID = CP.GROUP_AUTHOR_ID OR G.ID = CC.GROUP_AUTHOR_ID
				LEFT JOIN GROUP_CONTRIBUTOR AS GC ON GC.GROUP_ID = G.ID
        LEFT JOIN FOLLOWER AS F ON C.AUTHOR_ID = F.TARGET_ID
        LEFT JOIN GROUP_FOLLOWER AS GF ON C.GROUP_AUTHOR_ID = GF.GROUP_ID
        LEFT JOIN EXPLANATION_COMMENT_TAG AS CT ON CT.REFERENCE_ID = EXPL.ID
      	LEFT JOIN COMMENT_TAG_FOLLOWER AS CTF ON CTF.TAG_ID = CT.TAG_ID;

CREATE OR REPLACE VIEW QUESTION_COMMENT_CONNECTIONS
AS
  SELECT QC.ID AS COMMENT_ID,
        Q.ASKER_ID AS ASKER_ID,
				Q.SITE_ID,
				CP.AUTHOR_ID AS PARENT_COMMENT_AUTHOR_ID,
				CS.AUTHOR_ID AS SIBLING_COMMENT_AUTHOR_ID,
        CC.AUTHOR_ID AS CHILD_COMMENT_AUTHOR_ID,
				GC.USER_ID AS GROUP_CONTRIBUTOR_ID,
        F.USER_ID AS AUTHOR_FOLLOWER_ID,
        GF.USER_ID AS GROUP_FOLLOWER_ID,
        CTF.USER_ID AS TAG_FOLLOWER_ID
        FROM QUESTION_COMMENT AS QC
        LEFT JOIN QUESTION AS Q ON QC.ID = QC.QUESTION_ID
        LEFT JOIN QUESTION_COMMENT AS CP ON CP.ID = QC.COMMENT_ID
				LEFT JOIN QUESTION_COMMENT AS CS ON QC.COMMENT_ID = CS.COMMENT_ID
				LEFT JOIN QUESTION_COMMENT AS CC ON QC.ID = CC.COMMENT_ID
				LEFT JOIN GROUPING AS G ON G.ID = QC.GROUP_AUTHOR_ID OR Q.GROUP_ASKER_ID OR G.ID = CP.GROUP_AUTHOR_ID OR G.ID = CC.GROUP_AUTHOR_ID
				LEFT JOIN GROUP_CONTRIBUTOR AS GC ON GC.GROUP_ID = G.ID
        LEFT JOIN FOLLOWER AS F ON QC.AUTHOR_ID = F.TARGET_ID
        LEFT JOIN GROUP_FOLLOWER AS GF ON QC.GROUP_AUTHOR_ID = GF.GROUP_ID
        LEFT JOIN QUESTION_COMMENT_TAG AS QCT ON QCT.REFERENCE_ID = Q.ID
      	LEFT JOIN COMMENT_TAG_FOLLOWER AS CTF ON CTF.TAG_ID = QCT.TAG_ID;

-- CREATE OR REPLACE VIEW EXPLANATION_COMMENT_CONNECTIONS
-- AS
--   SELECT
--
-- CREATE OR REPLACE VIEW QUESTION_COMMENT_CONNECTIONS
-- AS
--   SELECT


CREATE OR REPLACE VIEW FOLLOWING
AS
  SELECT
        F.USER_ID,
        F.TARGET_ID,
        GF.GROUP_ID,
        QF.TAG_ID AS QUESTION_TAG_ID,
        EF.TAG_ID AS EXPLANATION_TAG_ID,
        CF.TAG_ID AS COMMENT_TAG_ID
        FROM FOLLOWER AS F
    LEFT JOIN GROUP_FOLLOWER AS GF ON F.USER_ID = GF.USER_ID
    LEFT JOIN QUESTION_TAG_FOLLOWER AS QF ON QF.USER_ID = GF.USER_ID
    LEFT JOIN COMMENT_TAG_FOLLOWER AS CF ON CF.USER_ID = GF.USER_ID
    LEFT JOIN EXPLANATION_TAG_FOLLOWER AS EF ON EF.USER_ID = GF.USER_ID;


CREATE OR REPLACE VIEW GROUPED_EXPLANATION_DETAIL
AS
  SELECT GE.EXPLANATION_ID,
      GE.GROUP_ID,
      IFNULL(SUM(LYKE), 0) AS LIKES,
      IFNULL(SUM(DISLIKE), 0) AS DISLIKES
    FROM GROUPED_EXPLANATION AS GE
    LEFT JOIN GROUPED_OPINION AS GO
      ON GE.EXPLANATION_ID = GO.EXPLANATION_ID AND GE.GROUP_ID = GO.GROUP_ID
            GROUP BY GE.GROUP_ID, GE.EXPLANATION_ID;

CREATE OR REPLACE VIEW ACCESSIBLE_GROUP
AS
  SELECT  GROUP_ID AS ID,
          IMAGE, NAME, DESCRIPTION, GC.EMAIL_NOTIFY, GC.IN_APP_NOTIFY,
          USER_ID,
          GC.ID AS CONTRIBUTOR_ID,
          LEVEL
    FROM GROUP_CONTRIBUTOR AS GC
    LEFT JOIN GROUPING AS G ON GC.GROUP_ID = G.ID
  UNION
  SELECT  ID,
          IMAGE, NAME, DESCRIPTION, EMAIL_NOTIFY, IN_APP_NOTIFY,
          CREATOR_ID AS USER_ID,
          -1 AS CONTRIBUTOR_ID,
          -1 AS LEVEL
    FROM GROUPING;

-- CREATE OR REPLACE VIEW GROUP_AUTH
--   SELECT NULL AS ID, CREATOR_ID AS USER_ID, GROUP_ID, 0 AS ADMIN FROM GROUP
--   UNION
--   SELECT * FROM GroupContributor

-- ==========================  VALUES  =====================--

INSERT INTO NOTIFICATION_TYPE (ID, VALUE) VALUES (1, 'Explanation');
INSERT INTO NOTIFICATION_TYPE (ID, VALUE) VALUES (2, 'ExplanationComment');
INSERT INTO NOTIFICATION_TYPE (ID, VALUE) VALUES (3, 'Question');
INSERT INTO NOTIFICATION_TYPE (ID, VALUE) VALUES (4, 'QuestionComment');

INSERT INTO SITE_PARTS (ID, VALUE) VALUES (1, 'http://');
INSERT INTO SITE_PARTS (ID, VALUE) VALUES (2, 'https://');
